# Generated by Django 5.2.8 on 2025-11-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="lyrics_file",
            field=models.FileField(upload_to="songs/audio/"),
        ),
    ]
