# Generated by Django 5.2.8 on 2025-11-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_recording'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={},
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to='myrecordings/'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
