# Generated by Django 5.2.8 on 2025-11-11 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0004_alter_recording_options_alter_recording_audio_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="song",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="songs.song",
            ),
        ),
    ]
