# Generated by Django 5.2.8 on 2025-11-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0005_alter_recording_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trial_end_date", models.DateTimeField()),
            ],
        ),
    ]
